tags: 
- name: "topic"
  description: "Everything about your Topic"
paths:
  /topics:
    get:
      tags:
      - "topic"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Topic"
definitions:
  Topic:
    type: object
    properties:
      code:
        type: string
      name:
        type: string
      description:
        type: string
